# Licensed under a 3-clause BSD style license - see LICENSE.rst
name: vodf-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - sphinx
  - pydata-sphinx-theme=0.10  # for some reason 0.11 causes exception
  - pip
  - pip:
      - sphinx_panels
