# Licensed under a 3-clause BSD style license - see LICENSE.rst
name: vodf-docs
channels:
  - conda-forge
dependencies:
  - sphinx
  - pydata-sphinx-theme
  - sphinxcontrib-plantuml
  - plantuml=1.2025.2
