@startuml
hide circles
hide methods
skinparam ClassBackgroundColor white-aliceblue
skinparam backgroundcolor transparent
skinparam DefaultFontSize 14
skinparam DefaultFontName "Arial"



<style>
package {
        LineColor gray
        FontColor gray
}

class {
        Header {
                FontColor #white
                BackgroundColor #8800ff
                FontStyle bold
        }
}

</style>



@enduml
