@startuml
!include ../common.inc
skinparam linetype ortho

package IVOA <<cloud>> {

        class SMOC
        class TMOC
        class STMOC
}

package VODF {
        package L1 {
                class SpatialCoverage {
                        + r_fov : float
                        ..optional..
                        + region : Region
                }

                class TemporalCoverage {
                        + t_start
                        + t_stop
                }

                class SpectralCoverage {
                        + energy_min
                        + energy_max
                }

                Coverage *-- SpatialCoverage
                Coverage *-- TemporalCoverage
                Coverage *-- SpectralCoverage
                TemporalCoverage *-d--- "0..1" IVOA.TMOC
                TemporalCoverage *-d--- "0..1" IVOA.STMOC
                SpatialCoverage *-d--- "0..1" IVOA.SMOC
                SpatialCoverage *-d--- "0..1" IVOA.STMOC


                class OnTime <<extern>>
                class Pointing <<extern>>
                TemporalCoverage ..> OnTime
                TemporalCoverage ..> Pointing
        }
}

@enduml
