@startuml
!include ../common.inc

package VODF.L1 {

        abstract class IRF
        abstract class IRFComponent
        class  EffectiveArea <<IRFComponent>>
        class BackgroundRate <<IRFComponent>>
        class EnergyMigration <<IRFComponent>>
        class PSF <<IRFComponent>>

        IRF *-d- "0..*" IRFComponent
        IRF <|-r---- StandardIRF

        StandardIRF *--- EffectiveArea
        StandardIRF *--- BackgroundRate
        StandardIRF *--- EnergyMigration
        StandardIRF *--- PSF

}
