@startuml
!include ../common.inc
skinparam linetype ortho

package IVOA <<cloud>> {
        class ObsCore <<extern>> {}
        class DataLink <<extern>> {}
        ObsCore -- DataLink
}

package VODF {
        class Facility
        class Instrument
        Facility -- Instrument : <<has>> >
}


package VODF.L1 {

        together {
                class DataRelease  {
                        + facility: Facility
                        + data_release_id
                        ..
                        ~ time_interval
                        ~ documentation_url
                        ..facility-specific properties..
                        ~ processing_configuration
                        ~ processing_pipeline_version
                        ~ ...
                }

                class Observation #line.bold {
                        + obs_id
                        --
                        ~ primary_particle_id
                        ~ temporal_coverage
                        ~ spatial_coverage
                        ~ energy_coverage
                        ~ ...
                }

                class ObservationCollection {

                }
        }

        ObsCore .r. Observation : "<<find>> >"
        DataLink .r. Observation : "<<access>> >"

        DataRelease "1" -- "1..*" ObservationCollection
        ObservationCollection "1" -- "1..*" Observation

        ' Insrument is contextual info, not a part, so only an association.
        Observation "1" --l-- "1" Instrument : used >
        Facility "1" -r-- "*" DataRelease

        ' Constituent parts of an observation
        Observation "1" o-- "1" Pointing
        Observation "1" o--  "1..*" OnTime

        Observation  "1" o-- "0..1" EventList
        Observation  "0..*" o--  "0..1" IRF

        IRF "1"  *-- "1..*" IRFComponent

}

@enduml
