@startuml
!include common.inc


package VODF.L1 {

        class SingleOnTime <<metadata>>
        class TimeSeriesOnTime <<table>>

        OnTime <|-- SingleOnTime
        OnTime <|-- TimeSeriesOnTime
}
@enduml
