@startuml
!include common.inc


package VODF.L1 {
        class NominalPointing
        class TimeSeriesPointing

        Pointing <|-- NominalPointing
        Pointing <|-- TimeSeriesPointing

        TimeSeriesPointing "1" o-- "1..*" PointingMeasurement
}
@enduml
