@startuml
!include common.inc


package VODF.L1 {
        class NominalPointing <<metadata>>
        class TimeSeriesPointing <<table>>

        Pointing <|-- NominalPointing
        Pointing <|-- TimeSeriesPointing
}
@enduml
