name: "Pull Request Docs Check"
on:
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Conda setup
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        auto-update-conda: true
        activate-environment: "vodf-docs"
        environment-file: environment.yaml
        python-version: "3.13"
        conda-remove-defaults: "true"  # only want conda-forge
        channels: conda-forge
    - name: conda-info
      run: |
        conda info
        conda list
    - name: run-sphinx
      shell: bash -l {0}
      run: |
        make html
    - name: build-pdf
      shell: bash -l {0}
      run: |
        sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra tex-gyre texlive-latex-extra latexmk texlive-luatex xindy
        make latexpdf
    - name: Upload PDF doc
      uses: actions/upload-artifact@v4
      with:
        name: vodf_documentation_pdf
        path: build/latex/vodf.pdf
